export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';

export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS';

export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';

export const GET_MINI_MEALS_SUCCESS = 'GET_MINI_MEALS_SUCCESS';
export const GET_FULL_MEALS_SUCCESS = 'GET_FULL_MEALS_SUCCESS';
export const GET_MINI_VEG_MEALS_SUCCESS = 'GET_MINI_VEG_MEALS_SUCCESS';
export const GET_FULL_VEG_MEALS_SUCCESS = 'GET_FULL_VEG_MEALS_SUCCESS';
export const GET_MINI_NONVEG_MEALS_SUCCESS = 'GET_MINI_NONVEG_MEALS_SUCCESS';
export const GET_FULL_NONVEG_MEALS_SUCCESS = 'GET_FULL_NONVEG_MEALS_SUCCESS';
export const GET_VEG_MEALS_SUCCESS = 'GET_VEG_MEALS_SUCCESS';
export const GET_NONVEG_MEALS_SUCCESS = 'GET_NONVEG_MEALS_SUCCESS';
export const GET_SWEETS_SUCCESS = 'GET_SWEETS_SUCCESS';
export const GET_SPECIALS_SUCCESS = 'GET_SPECIALS_SUCCESS';
